### ISSUE TITLE
Twitter button 

### ISSUE THREAD

**Issue by etiennebatise** [TeenQuotes/website#19]
**Description :**
Twitter button "Follow" at the top-right corner of the homepage is cut.

**Config :**
Firefox 31.0, Windows 8.

**Image :**
![tq](https://cloud.githubusercontent.com/assets/5644956/4037623/89e42a54-2ca6-11e4-9600-8095854bcd73.png)

**Comment by AntoineAugusti** [comment]
This is a know bug that happens when the page was not loaded properly. If you refresh maybe it'll load as expected. It affects many browsers and OS.

This happens since CSS and JS files are injected when the DOM is loaded (see https://github.com/TeenQuotes/website/commit/04c9c07fa23c2061d5f53a341765d5ed124e3b1a). I think that forcing a repaint just after will solve this problem but it doesn't seem right.

I tried this to improve the pagespeed score given by Google. Since it produces some errors like this, I plan to load CSS and JS files in the old fashion way.

**Comment by ThibaudDauce** [comment]
"Windows 8" Oo :P

**Comment by AntoineAugusti** [comment]
@ThibaudDauce It was unexpected coming from @etiennebatise!
